[package]
name = "lasermidi"
version = "0.1.0"
authors = ["Eitan Mosenkis <eitan@mosenkis.net>"]

[dependencies]
css-color-parser = "0.1"
docopt = "0.8"
# dxf = "0.3"
printpdf = "0.2.1"
rimd = "0.0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
